# Generated by Django 6.0.2 on 2026-02-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_leaverequest_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='day',
            field=models.CharField(max_length=20),
        ),
    ]
